package view;

import controller.ClienteController;
import dao.ClienteDAO;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import javax.swing.table.DefaultTableModel;
import model.Cliente;
import util.Validador;





public class CadastroClienteTela extends javax.swing.JInternalFrame {

    private final ClienteController controller;

    public CadastroClienteTela() {
        initComponents();
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        BasicInternalFrameUI ui = (BasicInternalFrameUI) this.getUI();
        ui.setNorthPane(null);
        controller = new ClienteController();
        carregarTabela();
    }

    public void carregarTabela() {

        DefaultTableModel modelo = (DefaultTableModel) jTableClienteCadastro.getModel();
        modelo.setNumRows(0);

        ClienteDAO dao = new ClienteDAO();

        try {

            for (Cliente c : dao.listar()) {

                modelo.addRow(new Object[]{
                    c.getIdC(),
                    c.getNomeC(),
                    c.getEmailC(),
                    c.getTelefoneC(),
                    c.getEnderecoC(),
                    c.getWhatsappC(),
                    c.getAlergiaC()

                });

            }

        } catch (Exception ErroSql) {
            JOptionPane.showMessageDialog(null, "Error ao carregar tabela" + ErroSql, "Erro", JOptionPane.ERROR_MESSAGE);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableClienteCadastro = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        BotaoApagar = new javax.swing.JButton();
        BotaoAlterar = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        BotaoLimpar = new javax.swing.JButton();
        CampoNomeC = new javax.swing.JFormattedTextField();
        CampoTelefoneC = new javax.swing.JFormattedTextField();
        CampoWhatsappC = new javax.swing.JFormattedTextField();
        CampoEmailC = new javax.swing.JFormattedTextField();
        CampoEnderecoC = new javax.swing.JFormattedTextField();
        CampoAlergiaC = new javax.swing.JFormattedTextField();

        setBackground(new java.awt.Color(51, 51, 255));
        setMaximumSize(new java.awt.Dimension(32767, 32767));
        setMinimumSize(new java.awt.Dimension(0, 0));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 102, 255));
        jLabel1.setText("Nome:");

        jTableClienteCadastro.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Nome", "E-mail", "Telefone", "Endereço", "WhatsApp", "Alergia"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableClienteCadastro.setSelectionBackground(new java.awt.Color(153, 102, 255));
        jTableClienteCadastro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableClienteCadastroMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableClienteCadastro);

        jLabel7.setBackground(new java.awt.Color(0, 0, 0));
        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(153, 102, 255));
        jLabel7.setText("Endereço:");

        jLabel8.setBackground(new java.awt.Color(0, 0, 0));
        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(153, 102, 255));
        jLabel8.setText("WhatsApp:");

        jLabel9.setBackground(new java.awt.Color(0, 0, 0));
        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(153, 102, 255));
        jLabel9.setText("Telefone:");

        jLabel10.setBackground(new java.awt.Color(0, 0, 0));
        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(153, 102, 255));
        jLabel10.setText("E-mail:");

        jLabel11.setBackground(new java.awt.Color(0, 0, 0));
        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(153, 102, 255));
        jLabel11.setText("Alergia:");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(153, 102, 255));
        jLabel12.setText("Cadastro de Cliente");

        jButton1.setBackground(new java.awt.Color(153, 102, 255));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Cadastrar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        BotaoApagar.setBackground(new java.awt.Color(153, 102, 255));
        BotaoApagar.setForeground(new java.awt.Color(255, 255, 255));
        BotaoApagar.setText("Apagar");
        BotaoApagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoApagarActionPerformed(evt);
            }
        });

        BotaoAlterar.setBackground(new java.awt.Color(153, 102, 255));
        BotaoAlterar.setForeground(new java.awt.Color(255, 255, 255));
        BotaoAlterar.setText("Alterar");
        BotaoAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoAlterarActionPerformed(evt);
            }
        });

        BotaoLimpar.setBackground(new java.awt.Color(153, 102, 255));
        BotaoLimpar.setForeground(new java.awt.Color(255, 255, 255));
        BotaoLimpar.setText("Limpar");
        BotaoLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoLimparActionPerformed(evt);
            }
        });

        CampoNomeC.setBackground(new java.awt.Color(204, 204, 204));
        CampoNomeC.setForeground(new java.awt.Color(0, 0, 0));
        CampoNomeC.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                CampoNomeCKeyTyped(evt);
            }
        });
        CampoNomeC.setDocument(new Validador(30));

        CampoTelefoneC.setBackground(new java.awt.Color(204, 204, 204));
        CampoTelefoneC.setForeground(new java.awt.Color(0, 0, 0));
        try {
            CampoTelefoneC.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) #####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        CampoTelefoneC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampoTelefoneCActionPerformed(evt);
            }
        });
        CampoTelefoneC.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                CampoTelefoneCKeyTyped(evt);
            }
        });
        CampoTelefoneC.setDocument(new Validador(15));

        CampoWhatsappC.setBackground(new java.awt.Color(204, 204, 204));
        CampoWhatsappC.setForeground(new java.awt.Color(0, 0, 0));
        try {
            CampoWhatsappC.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) #####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        CampoWhatsappC.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                CampoWhatsappCKeyTyped(evt);
            }
        });
        CampoWhatsappC.setDocument(new Validador(15));

        CampoEmailC.setBackground(new java.awt.Color(204, 204, 204));
        CampoEmailC.setForeground(new java.awt.Color(0, 0, 0));
        CampoEmailC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampoEmailCActionPerformed(evt);
            }
        });
        CampoEmailC.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                CampoEmailCKeyTyped(evt);
            }
        });
        CampoEmailC.setDocument(new Validador(35));

        CampoEnderecoC.setBackground(new java.awt.Color(204, 204, 204));
        CampoEnderecoC.setForeground(new java.awt.Color(0, 0, 0));
        CampoEnderecoC.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                CampoEnderecoCKeyTyped(evt);
            }
        });
        CampoEmailC.setDocument(new Validador(35));

        CampoAlergiaC.setBackground(new java.awt.Color(204, 204, 204));
        CampoAlergiaC.setForeground(new java.awt.Color(0, 0, 0));
        CampoAlergiaC.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                CampoAlergiaCKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(378, 378, 378)
                        .addComponent(BotaoLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(BotaoAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(BotaoApagar, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(215, 215, 215)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(132, 132, 132)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(CampoNomeC)
                            .addComponent(CampoTelefoneC)
                            .addComponent(CampoWhatsappC, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(1, 1, 1)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(CampoEmailC)
                                    .addComponent(CampoEnderecoC, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(CampoAlergiaC, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton1)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 53, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 631, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(73, 73, 73))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel10)
                    .addComponent(CampoNomeC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CampoEmailC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel7)
                    .addComponent(CampoTelefoneC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CampoEnderecoC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel8)
                    .addComponent(jButton1)
                    .addComponent(CampoWhatsappC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CampoAlergiaC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BotaoLimpar)
                    .addComponent(BotaoAlterar)
                    .addComponent(BotaoApagar))
                .addContainerGap(75, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotaoAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoAlterarActionPerformed

        Object id = jTableClienteCadastro.getValueAt(jTableClienteCadastro.getSelectedRow(), 0);

        String nome = CampoNomeC.getText();

        String telefone = CampoTelefoneC.getText();

        String email = CampoEmailC.getText();

        String endereco = CampoEnderecoC.getText();

        String whatsapp = CampoWhatsappC.getText();

        String alergia = CampoAlergiaC.getText();

        try {
            controller.atualizarCliente(id, nome, email, telefone, endereco, whatsapp, alergia);
            LimparCampos();
            carregarTabela();

        } catch (Exception ex) {
            Logger.getLogger(CadastroClienteTela.class.getName()).log(Level.SEVERE, null, ex);
        }
        carregarTabela();

    }//GEN-LAST:event_BotaoAlterarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        if (CampoNomeC.getText().isEmpty() && CampoTelefoneC.getText().isEmpty() && CampoEmailC.getText().isEmpty() && CampoEnderecoC.getText().isEmpty()
                && CampoWhatsappC.getText().isEmpty() && CampoAlergiaC.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Preencha os todos campos");
            CampoNomeC.requestFocus();
            CampoTelefoneC.requestFocus();
            CampoEmailC.requestFocus();
            CampoEnderecoC.requestFocus();
            CampoWhatsappC.requestFocus();
            CampoAlergiaC.requestFocus();

        } else {
            
            String nome = CampoNomeC.getText();

            String telefone = CampoTelefoneC.getText();

            String email = CampoEmailC.getText();

            String endereco = CampoEnderecoC.getText();

            String whatsapp = CampoWhatsappC.getText();

            String alergia = CampoAlergiaC.getText();

            try {
                controller.cadastrarCliente(nome, email, telefone, endereco, whatsapp, alergia);
                LimparCampos();
                carregarTabela();

            } catch (Exception ex) {
                Logger.getLogger(CadastroClienteTela.class.getName()).log(Level.SEVERE, null, ex);
            }

        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void BotaoApagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoApagarActionPerformed

        Object id = jTableClienteCadastro.getValueAt(jTableClienteCadastro.getSelectedRow(), 0);

        try {
            controller.deletarCliente(id);
            LimparCampos();
            carregarTabela();

        } catch (Exception ex) {
            Logger.getLogger(CadastroClienteTela.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_BotaoApagarActionPerformed

    private void BotaoLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoLimparActionPerformed
        LimparCampos();
        carregarTabela();
    }//GEN-LAST:event_BotaoLimparActionPerformed

    private void jTableClienteCadastroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableClienteCadastroMouseClicked
        CarregarCampos();
    }//GEN-LAST:event_jTableClienteCadastroMouseClicked

    private void CampoEmailCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampoEmailCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CampoEmailCActionPerformed

    private void CampoNomeCKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CampoNomeCKeyTyped
        String caracteres = "abcçdefghijklmnopqrstuvwxyzABCÇDEFGHIJQLMNOPQRSTUVWXYáéíóúâêîôûãõÁÉÍÓÚÂÊÎÔÛÃÕ ";
        if (!caracteres.contains(evt.getKeyChar() + "")) {
            evt.consume();
        }
    }//GEN-LAST:event_CampoNomeCKeyTyped

    private void CampoEmailCKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CampoEmailCKeyTyped
        String caracteres = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJQLMNOPQRSTUVWXY@_-.!#$%&'*+-/=?^`{|}~0123456789";
        if (!caracteres.contains(evt.getKeyChar() + "")) {
            evt.consume();
        }
    }//GEN-LAST:event_CampoEmailCKeyTyped

    private void CampoTelefoneCKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CampoTelefoneCKeyTyped
        String caracteres = "0123456789";
        if (!caracteres.contains(evt.getKeyChar() + "")) {
            evt.consume();
        }
    }//GEN-LAST:event_CampoTelefoneCKeyTyped

    private void CampoWhatsappCKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CampoWhatsappCKeyTyped
        String caracteres = "0123456789";
        if (!caracteres.contains(evt.getKeyChar() + "")) {
            evt.consume();
        }
    }//GEN-LAST:event_CampoWhatsappCKeyTyped

    private void CampoEnderecoCKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CampoEnderecoCKeyTyped
        String caracteres = "abcçdefghijklmnopqrstuvwxyzABCÇDEFGHIJQLMNOPQRSTUVWXYáéíóúâêîôûãõÁÉÍÓÚÂÊÎÔÛÃÕ0123456789,- ";
        if (!caracteres.contains(evt.getKeyChar() + "")) {
            evt.consume();
        }
    }//GEN-LAST:event_CampoEnderecoCKeyTyped

    private void CampoAlergiaCKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CampoAlergiaCKeyTyped
        String caracteres = "abcçdefghijklmnopqrstuvwxyzABCÇDEFGHIJQLMNOPQRSTUVWXYáéíóúâêîôûãõÁÉÍÓÚÂÊÎÔÛÃÕ ";
        if (!caracteres.contains(evt.getKeyChar() + "")) {
            evt.consume();
        }
    }//GEN-LAST:event_CampoAlergiaCKeyTyped

    private void CampoTelefoneCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampoTelefoneCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CampoTelefoneCActionPerformed

    public void LimparCampos() {

        CampoNomeC.setText("");

        CampoTelefoneC.setText("");

        CampoEmailC.setText("");

        CampoEnderecoC.setText("");

        CampoWhatsappC.setText("");

        CampoAlergiaC.setText("");

    }

    public void CarregarCampos() {

        int setar = jTableClienteCadastro.getSelectedRow();

        CampoNomeC.setText(jTableClienteCadastro.getValueAt(setar, 1).toString());

        CampoEmailC.setText(jTableClienteCadastro.getValueAt(setar, 2).toString());
        CampoTelefoneC.setText(jTableClienteCadastro.getValueAt(setar, 3).toString());
        CampoEnderecoC.setText(jTableClienteCadastro.getValueAt(setar, 4).toString());
        CampoWhatsappC.setText(jTableClienteCadastro.getValueAt(setar, 5).toString());
        CampoAlergiaC.setText(jTableClienteCadastro.getValueAt(setar, 5).toString());

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotaoAlterar;
    private javax.swing.JButton BotaoApagar;
    private javax.swing.JButton BotaoLimpar;
    private javax.swing.JFormattedTextField CampoAlergiaC;
    private javax.swing.JFormattedTextField CampoEmailC;
    private javax.swing.JFormattedTextField CampoEnderecoC;
    private javax.swing.JFormattedTextField CampoNomeC;
    private javax.swing.JFormattedTextField CampoTelefoneC;
    private javax.swing.JFormattedTextField CampoWhatsappC;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTableClienteCadastro;
    // End of variables declaration//GEN-END:variables
}
